import { chromium } from "playwright";
import { mkdir } from "fs/promises";
const BASE = "http://localhost:8080";
const OUT = "/tmp/byvaro-promo2";
await mkdir(OUT, { recursive: true });
const b = await chromium.launch({ headless: true });
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } });
const p = await ctx.newPage();
await p.goto(`${BASE}/login`, { waitUntil: "networkidle" });
await p.locator("button", { hasText: "Arman Rahmanov" }).first().click();
await p.waitForURL(/\/inicio/, { timeout: 8000 });
await p.goto(`${BASE}/promociones/2`, { waitUntil: "networkidle" });
await p.waitForTimeout(800);
await p.screenshot({ path: `${OUT}/01-header.png`, fullPage: false });
await p.screenshot({ path: `${OUT}/02-full.png`, fullPage: true });
console.log("✓ done");
await b.close();
